# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('EmpId', models.AutoField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=45)),
                ('Address', models.CharField(max_length=45)),
                ('EmailId', models.EmailField(max_length=45, unique=True)),
                ('Password', models.CharField(max_length=300)),
                ('Phone', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Details',
                'managed': False,
            },
        ),
    ]
